apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: YWN0dWFsX3VzZXJuYW1l
  password: cGFzc3dvcmQ=

# apiVersion: v1
# kind: Secret
# metadata:
#   name: my-secret
# type: Opaque
# data:
#   username: dXNlcm5hbWU=
#   password: cGFzc3dvcmQ=
