apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  selector:
    app: my-influxdb
  type: NodePort
  ports:
  - port: 8086
    targetPort: 8086
    nodePort: 30008

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-influxdb
  template:
    metadata:
      labels:
        app: my-influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8086
